Modificato draw.io e aggiunto
SWEasabi/analisi-dei-requisiti pull request #90
Opened 2023-02-07 15:15 UTC by alessandro-massarenti

uc20 - visualizzazione lista ticket di guasto 
![Schermata del 2023-02-07 16-03-13](https://user-images.githubusercontent.com/48263116/217284128-6609df22-0c98-4059-96c5-a9851bf4ecd0.png)

2023-02-08 13:04 UTC, casYy commented
Credo ci sia bisogno di una UC 20.1 "Visualizzazione singolo ticket".

2023-02-08 13:09 UTC, alessandro-massarenti commented
> Credo ci sia bisogno di una UC 20.1 "Visualizzazione singolo ticket".

Si mi sembra una buona idea, infatti è ancora una draft la pr. Linko il commento nella issue specifica.

2023-02-08 19:31 UTC, alessandro-massarenti commented
Ricapitolando, manca:

- [ ]  la stesura di uc02.1 #94 
- [ ] manca la stesura testuale UC20
- [ ] manca l'immagine di UC20
- [ ] manca stesura testuale di UC20.1
- [ ] manca l'immagine nel testo di UC20.1
- [ ] manca stesura testuale di UC20.1.1
- [ ] manca stesura testuale di UC20.1.2

Per 20 e 20.1 le imagini sono già nella cartella corretta.

UC20 è della issue #87

2023-02-08 19:42 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc05.tex
> +    \item l'utente visualizza l'intensità del lampione in quell'intervallo temporale.
```suggestion
\begin{enumerate}
    \item L'utente comunica al sistema di quale lampione vuole visualizzare l'intensità luminosa nel tempo;
    \item l'utente specifica l'intervallo temporale del quale vuole visualizzare le intensità del lampione;
    \item l'utente visualizza l'intensità del lampione in quell'intervallo temporale.
```

2023-02-08 19:42 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc25.tex
> +\end{enumerate}
Itemize perchè non sono sequenziali le precondizioni

```suggestion
\begin{itemize}
    \item L'attore primario è autenticato ed autorizzato dal sistema;
    \item l'area di illuminazione contiene almeno un lampione.
\end{itemize}
```

2023-02-08 19:42 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc26.tex
> +\end{enumerate}
La lampadina è connessa al sistema e autorizzata

```suggestion
\begin{itemize}
    \item L'attore primario ha precedentemente letto il dato dell'intensità luminosa.
\end{itemize}
```

2023-02-08 19:42 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc26.tex
> +    \item L'attore primario ha il valore dell'intensità luminosa da inserire;
```suggestion
    \item L'attore primario da al sistema il valore dell'intensità luminosa da inserire;
```

2023-02-08 19:42 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc26.tex
> +    \item L'attore primario ha inserito nel sistema il valore dell'intensità luminosa letto.
```suggestion
    \item Il sistema ha loggato l valore dell'intensità luminosa letto.
```

2023-02-09 14:42 UTC, bonni1207 commented
> Ricapitolando, manca:
> 
> * [x]   la stesura di uc02.1 [Manca stesura UC2.1 #94](https://github.com/SWEasabi/analisi-dei-requisiti/issues/94)
> * [x]  manca la stesura testuale UC20
> * [x]  manca l'immagine di UC20
> * [x]  manca stesura testuale di UC20.1
> * [x]  manca l'immagine nel testo di UC20.1
> * [x]  manca stesura testuale di UC20.1.1
> * [x]  manca stesura testuale di UC20.1.2
> 
> Per 20 e 20.1 le imagini sono già nella cartella corretta.
> 
> UC20 è della issue #87
> 
> @casYy , @bonni1207

Tutto fatto, ma non è più UC20, è UC07

2023-02-09 14:59 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc05.tex
> +    \item l'utente visualizza l'intensità del lampione in quell'intervallo temporale.
Risolta a mano da @bonni1207

2023-02-09 15:03 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc26.tex
> +\end{enumerate}
Risolto a mano da @bonni1207

2023-02-09 15:05 UTC, alessandro-massarenti commented on src-doc/contenuti/use-cases/uc26.tex
> +    \item L'attore primario ha il valore dell'intensità luminosa da inserire;
Risolto a mano da @bonni1207

2023-02-09 16:20 UTC, pierobonluca01 requested changes

2023-02-09 16:20 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc02.tex
> +\paragraph{Attore primario} L'attore primario è o l'utente gestore manutentore.
```suggestion
\paragraph{Attore primario} L'attore primario è o l'utente gestore o l'utente manutentore.
```

2023-02-09 16:35 UTC, pierobonluca01 requested changes

2023-02-09 16:35 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc14.tex
> +\paragraph{Precondizioni} L'attore primario è autenticato ed autorizzato dal sistema. Inoltre, il sensore che l'attore primario vuole rimuovere è presente.
Non chiaro.

2023-02-09 16:52 UTC, pierobonluca01 requested changes

2023-02-09 16:52 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc15.tex
> +\paragraph{Precondizioni} L'attore primario è autenticato ed autorizzato dal sistema. Inoltre, il lampione che l'attore primario vuole rimuovere è presente.
Non chiaro.

2023-02-09 16:52 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc26.tex
> +\paragraph{Intenzione in contesto} L'attore primario vuole impostare un'area di illuminazione in modalità \textit{upper\_state}
```suggestion
\paragraph{Intenzione in contesto} L'attore primario vuole impostare un'area di illuminazione in modalità \textit{lower\_state}
```

2023-02-09 16:52 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc26.tex
> +    \item il sistema comunica all'attore primario la conferma dell'impostazione in upper state dell'area di gestione.
```suggestion
    \item il sistema comunica all'attore primario la conferma dell'impostazione in lower state dell'area di gestione.
```

2023-02-09 20:52 UTC, bonni1207 commented on src-doc/contenuti/use-cases/uc23.tex
> +
Ora correggo.

2023-02-09 20:58 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc14.tex
> +\paragraph{Precondizioni} L'attore primario è autenticato ed autorizzato dal sistema. Inoltre, il sensore che l'attore primario vuole rimuovere è presente.
```suggestion
\paragraph{Precondizioni} L'attore primario è autenticato ed autorizzato dal sistema. Inoltre, il sensore, che l'attore primario vuole rimuovere, è presente.
```

2023-02-09 20:59 UTC, pierobonluca01 commented on src-doc/contenuti/use-cases/uc15.tex
> +\paragraph{Precondizioni} L'attore primario è autenticato ed autorizzato dal sistema. Inoltre, il lampione che l'attore primario vuole rimuovere è presente.
```suggestion
\paragraph{Precondizioni} L'attore primario è autenticato ed autorizzato dal sistema. Inoltre, il lampione, che l'attore primario vuole rimuovere, è presente.
```

2023-02-10 14:52 UTC, merged